version: '3.8'

services:
  app:
    image: hello-front-dev
    build:
      context: . 
      dockerfile: dev.Dockerfile 
    ports:
      - 5173:5173
    container_name: hello-front-dev 
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules