services:
  # Backend Service
  dev:
    build:
      context: ./todo-backend
      dockerfile: Dockerfile.dev
    ports:
      - 3002:3002
    env_file:
      - ./todo-backend/.env
    container_name: backend

  # Frontend Service
  app:
    build:
      context: ./todo-frontend
      dockerfile: dev.Dockerfile
    ports:
      - 5173:5173
    container_name: frontend

  # MongoDB Service
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./mongo_data:/data/db

  # Redis Service
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data

  # Nginx Service
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - dev
      - app
